

excludes = [
  # *Nonlinear.dfy in Arithmetic/Internals/ are subject to the options here
  "**/Arithmetic/*.dfy", "**/Arithmetic/**/*Internals.dfy",
  # Built per-target language instead
  "**/TargetSpecific/*.dfy"
]

[options]
# Options that help support more values of consuming context options
# (mostly turning on any more restrictive verification)
track-print-effects = true
enforce-determinism = true
reads-clauses-on-methods = true

# Options important for sustainable development
# of the libraries themselves.
resource-limit = 1000
warn-as-errors = true
# These give too many false positives right now, but should be enabled in the future
warn-redundant-assumptions = false
warn-contradictory-assumptions = false
