name: Check Deep Tests (Reusable Workflow)

on:
  workflow_call:
    inputs:
      sha:
        type: string
      branch:
        type: string

jobs:
  check-deep-tests:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Dafny
      uses: actions/checkout@v3
      with:
        path: dafny
        submodules: true
    - uses: actions/github-script@v6
      if: github.repository_owner == 'dafny-lang'
      with:
        script: |
          const script = require('${{ github.workspace }}/dafny/.github/workflows/check-for-workflow-run.js')
          console.log(script({github, context, core,
                              workflow_id: 'deep-tests.yml',
                              ...('${{ inputs.sha }}' ? {sha: '${{ inputs.sha }}'} : {}),
                              ...('${{ inputs.branch }}' ? {branch: '${{ inputs.branch }}'} : {})}))
