
# This workflow includes more expensive tests than what is run on every PR, that are unlikely to break on most changes.
# It also publishes a nightly release.
name: Nightly test and release workflow

on:
  schedule:
    # Chosen to be hopefully outside of business hours for most contributors'
    # time zones, and not on the hour to avoid heavy scheduled-job times:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  deep-integration-tests:
    if: github.repository_owner == 'dafny-lang'
    uses: ./.github/workflows/integration-tests-reusable.yml
    with:
      all_platforms: true
      num_shards: 5

  determine-vars:
    if: github.repository_owner == 'dafny-lang'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Dafny
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.sha }}

      - name: Get short sha
        id: short-sha
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    outputs:
      short-sha: ${{ steps.short-sha.outputs.sha_short }}
      date: ${{ steps.date.outputs.date }}
      name: nightly-${{ steps.date.outputs.date }}-${{ steps.short-sha.outputs.sha_short }}

  publish-release:
    if: github.repository_owner == 'dafny-lang'
    uses: ./.github/workflows/publish-release-reusable.yml
    needs: [deep-integration-tests, determine-vars]
    with:
      name: ${{ needs.determine-vars.outputs.name }}
      sha: ${{ github.sha }}
      tag_name: nightly
      release_nuget: true
      draft: false
      release_notes: "This is an automatically published nightly release. This release is not as stable as versioned releases and does not contain release notes."
      prerelease: true
    secrets:
      nuget_api_key: ${{ secrets.NUGET_API_KEY }}
