name: .NET Core

on: [ push, pull_request ]

jobs:
  draft_release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{steps.draft_release.outputs.upload_url}}
    steps:
    - name: Create Release Draft
      id: draft_release
      uses: actions/create-release@v1
      if: ${{github.event_name == 'push' && contains(github.ref, 'refs/tags/')}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: {{github.ref}}
        release_name: ${{github.ref}}
        draft: true
  build:
    needs: [draft_release]
    runs-on: ${{matrix.os}}
    name: ${{matrix.suffix}}
    strategy:
      matrix:
        include:
          - os: ubuntu-16.04
            suffix: ubuntu-16.04
            z3: z3-4.8.5-x64-ubuntu-16.04
            chmod: true
            coverage: true
          - os: windows-2019
            suffix: win
            z3: z3-4.8.5-x64-win
            chmod: false
            coverage: false
          - os: macos-10.15
            suffix: osx-10.14.1
            z3: z3-4.8.5-x64-osx-10.14.2
            chmod: true
            coverage: false
    env:
      publishPath: publish
      testPath: Source/DafnyLS.IntegrationTest/bin/Debug/net5.0
      solutionPath: Source/DafnyLS.sln
      z3BaseUri: https://github.com/Z3Prover/z3/releases/download/Z3-4.8.5
      coverageFile: coverage.cobertura.xml
      artifactName: DafnyLS-${{matrix.suffix}}
    outputs:
      binaries: ${{env.publishPath}}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup .NET Core 3.1 # Required by the coco-runner
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install dependencies
      run: dotnet restore ${{env.solutionPath}}
    - name: Build
      run: dotnet build --configuration Release --no-restore ${{env.solutionPath}}
    - name: Load Z3
      shell: pwsh
      run: |
        Invoke-WebRequest ${{env.z3BaseUri}}/${{matrix.z3}}.zip -OutFile z3.zip
        Expand-Archive z3.zip .
        Remove-Item z3.zip
        Copy-Item ${{matrix.z3}} ${{env.testPath}}/z3 -Recurse
    - name: Set Permissions
      if: ${{matrix.chmod}}
      run: chmod +x ${{env.testPath}}/z3/bin/z3
    - name: Run Tests
      if: ${{!matrix.coverage}}
      run: dotnet test --no-restore --verbosity normal ${{env.solutionPath}}
    - name: Run Test Coverage
      if: ${{matrix.coverage}}
      run: |
        dotnet test --no-restore --verbosity normal --settings Source/DafnyLS.IntegrationTest/coverlet.runsettings ${{env.solutionPath}}
        mv Source/DafnyLS.IntegrationTest/TestResults/*/${{env.coverageFile}} ./${{env.coverageFile}}
    - name: Upload Coverage Report
      if: ${{matrix.coverage}}
      uses: codecov/codecov-action@v1
      with:
        file: ./${{env.coverageFile}}
    - name: Prepare Artifacts
      if: ${{github.ref == 'refs/heads/master'}}
      shell: pwsh
      run: |
        dotnet publish --configuration Release --no-restore -p:SatelliteResourceLanguages=en --output ${{env.publishPath}} dafny/Source/DafnyDriver/DafnyDriver.csproj
        dotnet publish --configuration Release --no-restore -p:SatelliteResourceLanguages=en --output ${{env.publishPath}} Source/DafnyLS/DafnyLS.csproj
        Copy-Item ${{matrix.z3}} ${{env.publishPath}}/z3 -Recurse
    - name: Upload Artifacts
      if: ${{github.ref == 'refs/heads/master'}}
      uses: actions/upload-artifact@v2
      with:
        name: ${{artifactName}}
        path: ${{env.publishPath}}/
    - name: Prepare Release Artifact
      if: ${{github.event_name == 'push' && contains(github.ref, 'refs/tags/')}}
      shell: pwsh
      run: Compress-Archive ${{env.publishPath}}/* ${{env.publishPath}}/${{artifactName}}.zip
    - name: Upload Release Artifact
      if: ${{github.event_name == 'push' && contains(github.ref, 'refs/tags/')}}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{needs.draft_release.outputs.upload_url}}
        asset_path: ${{env.publishPath}}/${{artifactName}}.zip
        asset_name: ${{artifactName}}.zip
        asset_content_type: application/zip
