name: "Integration Test Report"

on:
  workflow_run:
    workflows:
      - Integration Tests (Reusable Workflow)
    types:
      - completed

jobs:
  report:
    name: Download and Publish Test Results
    runs-on: ubuntu-latest
    if: always()

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        with:
          artifact: integration-test-results-ubuntu-20.04
          name: Build and Test Results
          path: "*.trx"
          reporter: dotnet-trx
